services:
  redis:
    image: redis
    container_name: bitwarp-redis-server
    ports:
      - "6379:6379"
    networks:
      - bitwarp-net

  tracker:
    image: bitwarp-tracker
    container_name: tracker
    ports:
      - "9999:9999"
    networks:
      - bitwarp-net
    depends_on:
      - redis

  node:
    image: bitwarp-node
    networks:
      - bitwarp-net
    volumes:
      - ./storage/warp:/root/storage/warp
    depends_on:
      - tracker
    command: [ "./node", "get", "storage/warp/kali-linux-2024.1-installer-amd64.iso.json" ]

  seeder:
    image: bitwarp-node
    networks:
      - bitwarp-net
    volumes:
      - ./storage:/root/storage
    depends_on:
      - tracker
    command: [ "./node", "seed", "storage/warp/kali-linux-2024.1-installer-amd64.iso.json" ]

networks:
  bitwarp-net:
    driver: bridge
